"""

coset_decoder.py
----------------------------------------------------------------------------
Coset free-energy (CFE) decoder for the fault-tolerant MDR circuits.

The optimal decoder compares the total probability of the two logical
classes (cosets) of errors that explain the syndrome,

    Z_l = sum_{E : H E = s, L E = l} prod_j p_j^{E_j} (1 - p_j)^{1 - E_j},

instead of the probability of the single most likely error. The CFE decoder
approximates the free energies F_l = -ln Z_l in three steps.

1. Two-class search. BP-OSD runs on the check matrix with the logical
   observable appended as an extra row, once with the observable bit set to
   0 and once with it set to 1. This returns a low-weight error E_l in each
   class. An optional guide (in this package the hierarchical correlated
   matching solution) supplies per-shot fault probabilities for a second
   BP-OSD run, which gives a second candidate in each class.
2. Local descent. A degeneracy move is a set of three or four fault
   mechanisms whose detector sets and observable sets add to zero. Applying
   a move changes neither the syndrome nor the class. Each E_l is improved by
   greedy moves until no move lowers its weight w(E) = sum_{j in E} lambda_j
   with lambda_j = ln[(1 - p_j)/p_j].
3. Free energy. Treating the moves that touch E_l as independent gives
   Z_l ~ e^{-w(E_l)} prod_g (1 + e^{-dw_g}), where dw_g is the weight change
   of move g. The decoder returns the class with the smaller

       F_l = w(E_l) - kappa * sum_g ln(1 + e^{-dw_g}).

   The factor kappa < 1 compensates for overlapping moves, which the
   independent-move product counts more than once. With several candidates
   per class the decoder keeps the one with the smallest F_l.
"""

from __future__ import annotations

import collections
from typing import List, Sequence, Tuple

import numpy as np
import scipy.sparse as sp


def _pairs_within_groups(group: np.ndarray, items: np.ndarray):
    """All pairs (items[i], items[j]), i < j, of entries with the same group label.

    `group` must be sorted. Pairs are generated by offset k = 1, 2, ... inside
    each run, so the work is the number of pairs and not the square of the
    largest run.
    """
    n = group.size
    if n < 2:
        return np.zeros(0, np.int64), np.zeros(0, np.int64)
    starts = np.flatnonzero(np.r_[True, group[1:] != group[:-1]])
    lens = np.diff(np.r_[starts, n])
    run_len = np.repeat(lens, lens)
    pos = np.arange(n) - np.repeat(starts, lens)
    left, right = [], []
    idx = np.flatnonzero(run_len - pos > 1)
    k = 1
    while idx.size:
        left.append(items[idx])
        right.append(items[idx + k])
        k += 1
        idx = idx[run_len[idx] - pos[idx] > k]
    return np.concatenate(left), np.concatenate(right)


def degeneracy_moves(mech_keys: Sequence[Tuple[Tuple[int, ...], Tuple[int, ...]]],
                     size4: bool = True) -> np.ndarray:
    """
    All moves of three or four mechanisms that leave syndrome and class unchanged.

    Three-mechanism moves are a hyperedge together with two mechanisms that
    add up to it. Four-mechanism moves are two pairs of adjacent mechanisms
    with the same combined detector set and observable set, for example the
    two ways around a square of the decoding graph. Returns an integer array
    of shape (num_moves, 4), padded with -1, in lexicographic order.

    The detector and observable sets are compared through random 64-bit
    hashes (XOR of one random word per detector), so the memory grows with the
    number of adjacent pairs and not with Python sets of sets. Every move is
    checked exactly at the end. The result equals degeneracy_moves_reference.
    """
    nm = len(mech_keys)
    if nm == 0:
        return np.full((0, 4), -1, dtype=np.int64)
    lens = np.fromiter((len(dd) for dd, _ in mech_keys), dtype=np.int64, count=nm)
    det = np.fromiter((x for dd, _ in mech_keys for x in dd), dtype=np.int64, count=int(lens.sum()))
    owner = np.repeat(np.arange(nm, dtype=np.int64), lens)
    nd = int(det.max()) + 1 if det.size else 1
    rng = np.random.default_rng(20250917)
    zd = rng.integers(1, np.iinfo(np.int64).max, size=nd, dtype=np.int64).view(np.uint64)
    hd = np.zeros(nm, dtype=np.uint64)
    np.bitwise_xor.at(hd, owner, zd[det])
    obs = [tuple(ob) for _, ob in mech_keys]
    nobs = 1 + max((max(ob) for ob in obs if ob), default=0)
    zo = rng.integers(1, np.iinfo(np.int64).max, size=nobs, dtype=np.int64).view(np.uint64)
    ho = np.fromiter((np.bitwise_xor.reduce(zo[list(ob)]) if ob else 0 for ob in obs),
                     dtype=np.uint64, count=nm)
    key = hd ^ ho

    # unordered pairs of mechanisms that share a detector
    order = np.argsort(det, kind="stable")
    a, b = _pairs_within_groups(det[order], owner[order])
    code = np.unique(np.minimum(a, b) * nm + np.maximum(a, b))
    a, b = code // nm, code % nm
    del code
    keep = hd[a] != hd[b]          # the detector part of the sum is not empty
    a, b = a[keep], b[keep]
    kp = key[a] ^ key[b]

    moves = []
    # three-mechanism moves: the sum of the pair is itself a mechanism
    srt = np.argsort(key, kind="stable")
    ks = key[srt]
    pos = np.searchsorted(ks, kp)
    pos = np.minimum(pos, nm - 1)
    hit = ks[pos] == kp
    c = srt[pos]
    hit &= (c != a) & (c != b)
    if hit.any():
        t3 = np.sort(np.stack([a[hit], b[hit], c[hit]], axis=1), axis=1)
        moves.append(np.concatenate([t3, np.full((len(t3), 1), -1, np.int64)], axis=1))
    # four-mechanism moves: two pairs with the same sum
    if size4 and a.size:
        o = np.argsort(kp, kind="stable")
        u, v = _pairs_within_groups(kp[o], o)
        q = np.stack([a[u], b[u], a[v], b[v]], axis=1)
        del u, v
        q.sort(axis=1)
        distinct = (q[:, 0] != q[:, 1]) & (q[:, 1] != q[:, 2]) & (q[:, 2] != q[:, 3])
        moves.append(q[distinct])
    if not moves:
        return np.full((0, 4), -1, dtype=np.int64)
    G = np.unique(np.concatenate(moves), axis=0)

    # exact check of every move (guards against hash collisions), in blocks to bound memory
    Hm = sp.csr_matrix((np.ones(det.size, dtype=np.int64), (owner, det)), shape=(nm, nd))
    Om = sp.csr_matrix((np.ones(sum(len(ob) for ob in obs), dtype=np.int64),
                        ([j for j, ob in enumerate(obs) for _ in ob], [o for ob in obs for o in ob])),
                       shape=(nm, nobs))
    ok = np.ones(len(G), dtype=bool)
    step = 500_000
    for s0 in range(0, len(G), step):
        blk = G[s0:s0 + step]
        rows = np.repeat(np.arange(len(blk)), 4)
        cols = blk.reshape(-1)
        m = cols >= 0
        Mv = sp.csr_matrix((np.ones(int(m.sum()), dtype=np.int64), (rows[m], cols[m])), shape=(len(blk), nm))
        for A in (Hm, Om):
            S = (Mv @ A).tocsr()
            S.data %= 2
            S.eliminate_zeros()
            ok[s0:s0 + step] &= np.diff(S.indptr) == 0
    G = G[ok]
    return G[np.lexsort(G.T[::-1])]


def degeneracy_moves_reference(mech_keys: Sequence[Tuple[Tuple[int, ...], Tuple[int, ...]]],
                     size4: bool = True) -> np.ndarray:
    """
    Reference implementation of degeneracy_moves with Python sets (small codes only).

    Three-mechanism moves are a hyperedge together with two mechanisms that
    add up to it. Four-mechanism moves are two pairs of adjacent mechanisms
    with the same combined detector set and observable set, for example the
    two ways around a square of the decoding graph. Returns an integer array
    of shape (num_moves, 4), padded with -1.
    """
    keys = [(frozenset(dd), frozenset(ob)) for dd, ob in mech_keys]
    index = {k: j for j, k in enumerate(keys)}
    det2m = collections.defaultdict(list)
    for j, (S, _) in enumerate(keys):
        for x in S:
            det2m[x].append(j)
    moves = set()
    for j, (S, O) in enumerate(keys):
        nb = set()
        for x in S:
            nb.update(det2m[x])
        for a in nb:
            if a == j:
                continue
            Sb, Ob = S ^ keys[a][0], O ^ keys[a][1]
            if not Sb:
                continue
            b = index.get((Sb, Ob))
            if b is not None and b not in (a, j):
                moves.add(tuple(sorted((j, a, b))))
    if size4:
        groups = collections.defaultdict(set)
        for ms in det2m.values():
            for i1 in range(len(ms)):
                for i2 in range(i1 + 1, len(ms)):
                    a, b = ms[i1], ms[i2]
                    K = (keys[a][0] ^ keys[b][0], keys[a][1] ^ keys[b][1])
                    if K[0]:
                        groups[K].add((min(a, b), max(a, b)))
        for prs in groups.values():
            prs = sorted(prs)
            for i1 in range(len(prs)):
                for i2 in range(i1 + 1, len(prs)):
                    s = set(prs[i1]) | set(prs[i2])
                    if len(s) == 4:
                        moves.add(tuple(sorted(s)))
    G = np.full((len(moves), 4), -1, dtype=np.int64)
    for i, m in enumerate(sorted(moves)):
        G[i, :len(m)] = m
    return G


class CosetFreeEnergyDecoder:
    """
    Two-class BP-OSD search, local descent and free-energy comparison.

    Parameters
    ----------
    H : scipy.sparse matrix Detector-by-mechanism check matrix.
    mech_keys : list of (detectors, observables) for each mechanism.
    priors : array of mechanism probabilities.
    kappa : float Weight of the entropy term (0 gives most-likely-error).
    osd_order : int Order of the combination-sweep OSD.
    bp_iters : int Iterations of product-sum BP before OSD.
    guide : callable or None Maps the detection events of a shot to fault
    probabilities for a second, guided BP-OSD run.
    gate : float or None If set, the guided run is skipped when the free
    energies of the unguided candidates already differ by more than `gate`.
    osd_method : str "osd_cs" (combination sweep, default) or "osd0" (no sweep).
    osd_impl : str "fast" (default) computes ldpc's OSD-CS decoding with
    `fast_osd.FastBpOsd`, which scores all candidates with one back-substitution;
    "ldpc" calls ldpc's BpOsdDecoder, whose candidate table needs memory that
    grows as the square of the number of fault mechanisms (about 0.5 GB at
    d = 9 and 80 GB at d = 21 with r = d). Both give the same decoding.
    """

    def __init__(self, H, mech_keys, priors, kappa: float = 0.5,
                 osd_order: int = 10, bp_iters: int = 30, guide=None,
                 gate: float | None = None, osd_method: str = "osd_cs",
                 osd_impl: str = "fast") -> None:
        from ldpc import BpOsdDecoder

        self.kappa = float(kappa)
        self.guide = guide
        self.gate = gate
        nm = len(mech_keys)
        L = np.zeros((1, nm), dtype=np.uint8)
        for j, (_, obs) in enumerate(mech_keys):
            if any(o != 0 for o in obs):
                raise ValueError("the CFE decoder supports one observable (L0).")
            if 0 in obs:
                L[0, j] = 1
        self.L = L[0].astype(bool)
        Haug = sp.vstack([sp.csr_matrix(H), sp.csr_matrix(L)]).tocsc()

        def make():
            if osd_method == "osd_cs" and osd_impl == "fast":
                # same decoding as ldpc's OSD-CS, without its k^2 candidate table
                from .fast_osd import FastBpOsd
                return FastBpOsd(Haug, priors, bp_iters=bp_iters, order=osd_order)
            return BpOsdDecoder(Haug.astype(np.uint8), error_channel=list(priors),
                                max_iter=bp_iters, bp_method="product_sum",
                                osd_method=osd_method,
                                osd_order=osd_order if osd_method != "osd0" else 0)

        self._osd = make()
        self._osd_guided = make() if guide is not None else None
        p = np.clip(np.asarray(priors, dtype=float), 1e-15, 0.5)
        self.lam = np.log((1 - p) / p)
        self._lam_ext = np.append(self.lam, 0.0)
        self.G = degeneracy_moves(mech_keys)
        rows, cols = [], []
        for i, g in enumerate(self.G):
            for j in g:
                if j >= 0:
                    rows.append(j)
                    cols.append(i)
        M = sp.csr_matrix((np.ones(len(rows), dtype=np.int8), (rows, cols)),
                          shape=(nm, len(self.G)))
        M.sort_indices()
        self._indptr = M.indptr.astype(np.int64)
        self._indices = M.indices.astype(np.int64)
        self.num_mechanisms = nm

    # ------------------------------------------------------------- pieces
    def _touched(self, mask: np.ndarray):
        """Moves that contain at least one fault of the error, and their weight changes."""
        idx = np.flatnonzero(mask[:-1])
        if idx.size == 0:
            return None, None
        starts = self._indptr[idx]
        lens = self._indptr[idx + 1] - starts
        tot = int(lens.sum())
        if tot == 0:
            return None, None
        offs = np.repeat(starts - np.cumsum(lens) + lens, lens) + np.arange(tot)
        mv = self._indices[offs]
        owner = np.repeat(idx, lens)
        g = self.G[mv]
        valid = g >= 0
        gg = np.where(valid, g, self.num_mechanisms)
        ine = mask[gg]
        # count every move once, from its first fault that lies in the error
        first = np.where(ine, gg, np.iinfo(np.int64).max).min(axis=1)
        keep = first == owner
        g, gg, valid, ine = g[keep], gg[keep], valid[keep], ine[keep]
        sign = np.where(ine, -1.0, 1.0)
        dw = np.sum(np.where(valid, sign * self._lam_ext[gg], 0.0), axis=1)
        return g, dw

    def descend(self, mask: np.ndarray, max_steps: int = 500) -> np.ndarray:
        """Apply the best weight-lowering move until none is left (in place)."""
        for _ in range(max_steps):
            g, dw = self._touched(mask)
            if g is None:
                break
            k = int(np.argmin(dw))
            if dw[k] >= -1e-9:
                break
            for j in g[k]:
                if j >= 0:
                    mask[j] = ~mask[j]
        return mask

    def free_energy(self, mask: np.ndarray) -> Tuple[float, float]:
        """Weight and local entropy of the error in `mask`."""
        w = float(self._lam_ext[mask].sum())
        g, dw = self._touched(mask)
        S = 0.0 if g is None else float(np.sum(np.logaddexp(0.0, -dw)))
        return w, S

    def _run(self, dec, det_row: np.ndarray) -> List[np.ndarray]:
        masks = []
        for ell in (0, 1):
            syn = np.concatenate([np.asarray(det_row, dtype=np.uint8), [ell]])
            e = np.asarray(dec.decode(syn.astype(np.uint8)), dtype=bool)
            mask = np.zeros(self.num_mechanisms + 1, dtype=bool)
            mask[:-1] = e
            masks.append(mask)
        return masks

    def class_candidates(self, det_row: np.ndarray) -> List[List[np.ndarray]]:
        """Candidate errors for class 0 and class 1.

        The first candidate of each class comes from BP-OSD with the prior
        probabilities. With a guide, a second BP-OSD run uses the per-shot
        probabilities returned by the guide, for example the priors raised
        on the faults of a matching solution.
        """
        out = [[m] for m in self._run(self._osd, det_row)]
        if self.guide is not None:
            self._osd_guided.update_channel_probs(list(self.guide(det_row)))
            for ell, m in enumerate(self._run(self._osd_guided, det_row)):
                out[ell].append(m)
        return out

    def _score(self, cands: List[np.ndarray]):
        best = None
        for mask in cands:
            self.descend(mask)
            w, s = self.free_energy(mask)
            f = w - self.kappa * s
            if best is None or f < best[0]:
                best = (f, w, s)
        return best

    def decode_shot(self, det_row: np.ndarray):
        """Return (predicted class, (F_0, F_1), (w_0, w_1), (S_0, S_1))."""
        if not np.any(det_row):
            return 0, (0.0, np.inf), (0.0, np.inf), (0.0, 0.0)
        if self.gate is not None and self.guide is not None:
            # unguided candidates first; the guided run only for close calls
            first = [self._score([m]) for m in self._run(self._osd, det_row)]
            if abs(first[1][0] - first[0][0]) > self.gate:
                best = first
            else:
                self._osd_guided.update_channel_probs(list(self.guide(det_row)))
                second = [self._score([m]) for m in self._run(self._osd_guided, det_row)]
                best = [min(a, b) for a, b in zip(first, second)]
        else:
            best = [self._score(c) for c in self.class_candidates(det_row)]
        F = tuple(b[0] for b in best)
        W = tuple(b[1] for b in best)
        S = tuple(b[2] for b in best)
        return int(F[1] < F[0]), F, W, S

    def decode_batch(self, dets: np.ndarray) -> np.ndarray:
        dets = np.asarray(dets, dtype=np.uint8)
        out = np.zeros((dets.shape[0], 1), dtype=bool)
        for i in range(dets.shape[0]):
            out[i, 0] = bool(self.decode_shot(dets[i])[0])
        return out
