"""
analysis_reporting.py
---------------------
Analysis helpers for notebooks and reports built from saved MDR data.

This module keeps notebook-oriented loading, tabulation, and plotting logic
out of `analysis_plots.ipynb` so the notebook can remain a thin orchestration
layer. The classes here operate only on saved CSV outputs and analysis tables;
they do not run new simulations.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Tuple

from matplotlib import pyplot as plt
import pandas as pd

from .mdr_noise_sweep import MdrNoiseSweep
from .plotters import MdrNoiseSweepPlotter
from .workflows import resolve_family_search_dirs


class NotebookThresholdAnalysis:
    """
    Load saved sweep CSVs and produce notebook threshold figures.
    Supports resolving saved result files for multiple distances, recording
    provenance, and plotting threshold-style logical-fidelity curves.

    Attributes
    ----------
    results_dir : Path
        Directory containing saved sweep CSVs and spec sidecar JSON files.
    plots_dir : Path
        Base output directory for threshold figures generated by the notebook.
    distances : List[int]
        Code distances searched when loading saved sweep files.
    noise_models : Dict[str, str]
        Mapping from internal noise-model key to display label prefix.

    Methods
    -------
    __init__(...)
        Configure the saved-results directories and notebook plotting
        metadata.
    resolve_result_csv(noise_model, distance, p_spam)
        Resolve the most recent saved sweep CSV for one noise model,
        distance, SPAM setting, and recovery/correction configuration.
    load_sweeps_for_p_spam(p_spam, recovery_mode, correction_mode)
        Load all saved sweeps for a given SPAM setting and return both the
        in-memory sweeps and a provenance dataframe.
    load_correction_mode_comparison(distance, p_spam, recovery_mode,
        correction_modes)
        Load saved sweeps for one distance with multiple correction modes so
        they can be overlaid on the same threshold figures.
    plot_threshold_suite(sweeps_by_model, output_label)
        Plot one threshold figure per noise model from previously loaded
        sweeps.
    """

    def __init__(
        self,
        results_dir: str | Path,
        plots_dir: str | Path,
        distances: List[int],
        noise_models: Dict[str, str],
        code_family: str = "xyz2",
    ) -> None:
        """
        Configure notebook threshold analysis from saved sweep outputs.

        Args:
            results_dir: Directory containing saved sweep CSVs and spec JSON
                sidecars.
            plots_dir: Base output directory for threshold figures.
            distances: Code distances to search when loading saved data.
            noise_models: Mapping from internal noise-model key to display
                label prefix.
            code_family: Code family whose saved results should be loaded.
        """
        self.results_dir = Path(results_dir)
        self.plots_dir = Path(plots_dir)
        self.plots_dir.mkdir(parents=True, exist_ok=True)
        self.distances = list(distances)
        self.noise_models = dict(noise_models)
        self.code_family = code_family

    @staticmethod
    def _close(a: float, b: float, tol: float = 1e-15) -> bool:
        """
        Compare two floating-point values with a strict absolute tolerance.

        Args:
            a: First value.
            b: Second value.
            tol: Absolute tolerance.

        Returns:
            bool: True when the values differ by at most `tol`.
        """
        return abs(float(a) - float(b)) <= tol

    def resolve_result_csv(
        self,
        noise_model: str,
        distance: int,
        p_spam: float,
        recovery_mode: str | None = None,
        correction_mode: str | None = None,
    ) -> Path:
        """
        Resolve the newest saved sweep CSV for one configuration.

        The loader searches spec sidecar JSON files for the requested SPAM
        setting and optional recovery/correction modes. When multiple matching
        spec files exist, the newest CSV by modified time is returned. As a
        final fallback, the historical no-SPAM flat filename is accepted only
        when no explicit recovery or correction mode filter was requested.

        Args:
            noise_model: Internal noise-model key.
            distance: Code distance.
            p_spam: Requested SPAM setting.
            recovery_mode: Optional recovery timing mode filter.
            correction_mode: Optional correction implementation mode filter.

        Returns:
            Path: Resolved CSV path.

        Raises:
            FileNotFoundError: If no matching CSV can be found.
        """
        matches: List[Path] = []
        direct_candidates: List[Path] = []
        for search_dir in resolve_family_search_dirs(
            self.results_dir,
            self.code_family,
        ):
            family_direct_candidates = [
                search_dir / f"results_{self.code_family}_{noise_model}_d{distance}.csv"
            ]
            if self.code_family == "xyz2":
                family_direct_candidates.append(
                    search_dir / f"results_{noise_model}_d{distance}.csv"
                )
            direct_candidates.extend(family_direct_candidates)

            pattern_candidates = [
                f"results_{self.code_family}_{noise_model}_d{distance}_*.spec.json"
            ]
            if self.code_family == "xyz2":
                pattern_candidates.append(
                    f"results_{noise_model}_d{distance}_*.spec.json"
                )

            for spec_pattern in pattern_candidates:
                for spec_path in sorted(search_dir.glob(spec_pattern)):
                    spec = json.loads(spec_path.read_text(encoding="utf-8"))
                    if not self._close(float(spec.get("p_spam", -1.0)), p_spam):
                        continue
                    if str(spec.get("code_family", "xyz2")) != self.code_family:
                        continue
                    if recovery_mode is not None and (
                        str(spec.get("recovery_mode", "each_round"))
                        != recovery_mode
                    ):
                        continue
                    if correction_mode is not None and (
                        str(spec.get("correction_mode", "physical"))
                        != correction_mode
                    ):
                        continue
                    csv_path = spec_path.with_suffix("").with_suffix(".csv")
                    if csv_path.exists():
                        matches.append(csv_path)

        if not matches:
            for direct_csv in direct_candidates:
                if (
                    direct_csv.exists()
                    and self._close(p_spam, 0.0)
                    and recovery_mode is None
                    and correction_mode is None
                ):
                    return direct_csv
            raise FileNotFoundError(
                "No saved results for "
                f"noise_model={noise_model}, d={distance}, p_spam={p_spam:g}, "
                f"recovery_mode={recovery_mode}, "
                f"correction_mode={correction_mode}"
            )

        matches.sort(key=lambda path: path.stat().st_mtime, reverse=True)
        return matches[0]

    def load_sweeps_for_p_spam(
        self,
        p_spam: float,
        recovery_mode: str | None = None,
        correction_mode: str | None = None,
    ) -> Tuple[Dict[str, Dict[str, MdrNoiseSweep]], pd.DataFrame]:
        """
        Load all saved sweep CSVs for one SPAM setting.

        Args:
            p_spam: Requested SPAM setting.
            recovery_mode: Optional recovery timing mode filter.
            correction_mode: Optional correction implementation mode filter.

        Returns:
            Tuple[Dict[str, Dict[str, MdrNoiseSweep]], pd.DataFrame]:
            `(sweeps_by_model, records_df)` where the dataframe records the
            source CSV used for each loaded sweep.
        """
        sweeps_by_model: Dict[str, Dict[str, MdrNoiseSweep]] = {}
        records: List[Dict[str, object]] = []

        for noise_model, label in self.noise_models.items():
            sweeps: Dict[str, MdrNoiseSweep] = {}
            for distance in self.distances:
                try:
                    csv_path = self.resolve_result_csv(
                        noise_model=noise_model,
                        distance=distance,
                        p_spam=p_spam,
                        recovery_mode=recovery_mode,
                        correction_mode=correction_mode,
                    )
                except FileNotFoundError:
                    continue

                display_label = f"{label} (d={distance})"
                sweeps[display_label] = MdrNoiseSweep(load_data_filename=csv_path)
                records.append(
                    {
                        "noise_model": noise_model,
                        "display_label": display_label,
                        "distance": distance,
                        "p_spam": p_spam,
                        "recovery_mode": recovery_mode,
                        "correction_mode": correction_mode,
                        "csv_path": str(csv_path),
                    }
                )
            sweeps_by_model[noise_model] = sweeps

        records_df = pd.DataFrame(records)
        if not records_df.empty:
            records_df = records_df.sort_values(
                ["noise_model", "distance"]
            ).reset_index(drop=True)
        return sweeps_by_model, records_df

    def load_correction_mode_comparison(
        self,
        distance: int,
        p_spam: float,
        recovery_mode: str,
        correction_modes: Dict[str, str] | None = None,
    ) -> Tuple[Dict[str, Dict[str, MdrNoiseSweep]], pd.DataFrame]:
        """
        Load one-distance sweeps for multiple correction implementations.

        This helper is used by the notebook when comparing standard physical
        recovery against Pauli-frame recovery on the same threshold axes.

        Args:
            distance: Code distance to compare.
            p_spam: Requested SPAM setting.
            recovery_mode: Recovery timing mode shared by all compared runs.
            correction_modes: Mapping from legend label to correction-mode key.
                If omitted, `Physical` and `Pauli Frame` are loaded.

        Returns:
            Tuple[Dict[str, Dict[str, MdrNoiseSweep]], pd.DataFrame]:
            `(sweeps_by_model, records_df)` with one sweep per correction mode
            under each noise-model panel.
        """
        if correction_modes is None:
            correction_modes = {
                "Physical": "physical",
                "Pauli Frame": "pauli_frame",
            }

        sweeps_by_model: Dict[str, Dict[str, MdrNoiseSweep]] = {}
        records: List[Dict[str, object]] = []
        for noise_model in self.noise_models:
            sweeps: Dict[str, MdrNoiseSweep] = {}
            for display_name, correction_mode in correction_modes.items():
                try:
                    csv_path = self.resolve_result_csv(
                        noise_model=noise_model,
                        distance=distance,
                        p_spam=p_spam,
                        recovery_mode=recovery_mode,
                        correction_mode=correction_mode,
                    )
                except FileNotFoundError:
                    continue

                legend_label = f"{display_name} (d={distance})"
                sweeps[legend_label] = MdrNoiseSweep(load_data_filename=csv_path)
                records.append(
                    {
                        "noise_model": noise_model,
                        "display_label": legend_label,
                        "distance": distance,
                        "p_spam": p_spam,
                        "recovery_mode": recovery_mode,
                        "correction_mode": correction_mode,
                        "csv_path": str(csv_path),
                    }
                )
            sweeps_by_model[noise_model] = sweeps

        records_df = pd.DataFrame(records)
        if not records_df.empty:
            records_df = records_df.sort_values(
                ["noise_model", "correction_mode"]
            ).reset_index(drop=True)
        return sweeps_by_model, records_df

    def plot_threshold_suite(
        self,
        sweeps_by_model: Dict[str, Dict[str, MdrNoiseSweep]],
        output_label: str,
        metric: str = "observable_loss",
    ) -> List[Path]:
        """
        Plot one threshold figure per noise model from loaded sweep data.

        Args:
            sweeps_by_model: Mapping produced by
                :meth:`load_sweeps_for_p_spam`.
            output_label: Filename tag such as `no_spam` or `with_spam`.
            metric: Threshold metric to plot. Supported values are
                `observable_loss` for the original `1 - |<O>|` quantity and
                `state_prep_error` as a backwards-compatible alias for the
                restored Logical-X error plot.

        Returns:
            List[Path]: Output PDF paths that were written.

        Raises:
            ValueError: If `metric` is unsupported.
        """
        saved_paths: List[Path] = []
        for noise_model in self.noise_models:
            sweeps = sweeps_by_model.get(noise_model, {})
            if not sweeps:
                continue
            filename = (
                f"threshold_{self.code_family}_{noise_model}_{output_label}.pdf"
            )
            save_path = self.plots_dir / filename
            if metric == "state_prep_error":
                MdrNoiseSweepPlotter.plot_state_prep_error_multi(
                    sweeps=sweeps,
                    rounds=[1],
                    logical_label="Logical X",
                    overlay=False,
                    log_x=True,
                    save_path=save_path,
                    allow_legacy_approx=False,
                )
            elif metric == "observable_loss":
                MdrNoiseSweepPlotter.plot_error_multi(
                    sweeps=sweeps,
                    category="logical",
                    rounds=[1],
                    subset=["Logical X"],
                    overlay=False,
                    log_x=True,
                    save_path=save_path,
                )
            else:
                raise ValueError(
                    "metric must be 'state_prep_error' or 'observable_loss'."
                )
            saved_paths.append(save_path)
        return saved_paths


class NotebookFinalRoundAnalysis:
    """
    Load saved final-round-recovery replicate data and produce notebook plots.
    Supports building summary tables and plotting stabilizer and logical
    fidelity versus MDR rounds from a saved replicate dataset.

    Attributes
    ----------
    dataset_csv : Path
        CSV file containing saved replicate-level final-round-recovery data.
    plots_dir : Path
        Output directory for notebook final-round fidelity figures.
    dataset : pd.DataFrame | None
        Loaded dataset cached on the instance after `load_dataset()`.

    Methods
    -------
    __init__(...)
        Configure the saved dataset path and output plot directory.
    load_dataset()
        Load and validate the saved final-round replicate dataset.
    build_round_summary_table()
        Build a compact round-by-round mean fidelity table from the loaded
        dataset.
    plot_fidelity(category, save_path, figsize, show_violin, show_replicates)
        Plot fidelity versus MDR rounds for either stabilizers or logicals.
    plot_combined_fidelity(save_path, figsize)
        Plot stabilizer and logical fidelity panels in one combined figure.
    """

    def __init__(
        self,
        dataset_csv: str | Path,
        plots_dir: str | Path,
    ) -> None:
        """
        Configure final-round notebook analysis from a saved dataset.

        Args:
            dataset_csv: CSV containing saved replicate-level final-round
                fidelity data.
            plots_dir: Output directory for notebook-generated figures.
        """
        self.dataset_csv = Path(dataset_csv)
        self.plots_dir = Path(plots_dir)
        self.plots_dir.mkdir(parents=True, exist_ok=True)
        self.dataset: pd.DataFrame | None = None

    def load_dataset(self) -> pd.DataFrame:
        """
        Load and validate the saved final-round replicate dataset.

        Returns:
            pd.DataFrame: Loaded dataset.

        Raises:
            FileNotFoundError: If the dataset file does not exist.
            ValueError: If required columns are missing.
        """
        if not self.dataset_csv.exists():
            raise FileNotFoundError(f"Missing analysis dataset: {self.dataset_csv}")

        df = pd.read_csv(self.dataset_csv)
        expected = {
            "noise_model",
            "display_name",
            "category",
            "operator",
            "round",
            "replicate_idx",
            "fidelity",
            "p_spam",
            "recovery_mode",
            "shots",
            "num_replicates",
            "distance",
        }
        missing = expected - set(df.columns)
        if missing:
            raise ValueError(f"Dataset is missing columns: {sorted(missing)}")

        self.dataset = df
        return df

    def _require_dataset(self) -> pd.DataFrame:
        """
        Return the loaded dataset, loading it lazily when needed.

        Returns:
            pd.DataFrame: Cached dataset.
        """
        if self.dataset is None:
            return self.load_dataset()
        return self.dataset

    def build_round_summary_table(self) -> pd.DataFrame:
        """
        Build a compact round-by-round mean fidelity summary table.

        Returns:
            pd.DataFrame: Table containing average stabilizer fidelity and the
            three logical fidelities for each display label and round.
        """
        df = self._require_dataset()
        avg_stabilizer = (
            df[df["category"] == "stabilizer"]
            .groupby(["display_name", "round"], as_index=False)["fidelity"]
            .mean()
            .rename(columns={"fidelity": "avg_stabilizer_fidelity"})
        )
        logical_x = (
            df[(df["category"] == "logical") & (df["operator"] == "Logical X")]
            .groupby(["display_name", "round"], as_index=False)["fidelity"]
            .mean()
            .rename(columns={"fidelity": "logical_x_fidelity"})
        )
        logical_y = (
            df[(df["category"] == "logical") & (df["operator"] == "Logical Y")]
            .groupby(["display_name", "round"], as_index=False)["fidelity"]
            .mean()
            .rename(columns={"fidelity": "logical_y_fidelity"})
        )
        logical_z = (
            df[(df["category"] == "logical") & (df["operator"] == "Logical Z")]
            .groupby(["display_name", "round"], as_index=False)["fidelity"]
            .mean()
            .rename(columns={"fidelity": "logical_z_fidelity"})
        )
        summary = avg_stabilizer.merge(logical_x, on=["display_name", "round"])
        summary = summary.merge(logical_y, on=["display_name", "round"])
        summary = summary.merge(logical_z, on=["display_name", "round"])
        return summary.sort_values(["display_name", "round"]).reset_index(drop=True)

    @staticmethod
    def _operator_style_map(operators: List[str]) -> Dict[str, Tuple[str, str]]:
        """
        Assign stable colors and markers to operators.

        Args:
            operators: Operator labels that appear in a plot.

        Returns:
            Dict[str, Tuple[str, str]]: Mapping from operator to `(color,
            marker)`.
        """
        colors = plt.rcParams["axes.prop_cycle"].by_key()["color"]
        markers = [
            "o",
            "s",
            "^",
            "v",
            "<",
            ">",
            "8",
            "p",
            "P",
            "*",
            "h",
            "H",
            "+",
            "x",
            "X",
            "D",
            "d",
            "|",
            "_",
            ".",
        ]
        style_map: Dict[str, Tuple[str, str]] = {}
        for idx, operator in enumerate(operators):
            style_map[operator] = (
                colors[idx % len(colors)],
                markers[(idx // len(colors)) % len(markers)],
            )
        return style_map

    def plot_fidelity(
        self,
        category: str,
        save_path: str | Path,
        figsize: Tuple[int, int],
        show_violin: bool = True,
        show_replicates: bool = True,
    ) -> Path:
        """
        Plot fidelity versus MDR rounds for one category.

        Args:
            category: Either `stabilizer` or `logical`.
            save_path: Destination PDF path.
            figsize: Figure size in inches.
            show_violin: If True, overlay violin plots of replicate values.
            show_replicates: If True, overlay replicate scatter points.

        Returns:
            Path: Written output path.

        Raises:
            ValueError: If `category` is invalid.
        """
        if category not in {"stabilizer", "logical"}:
            raise ValueError("category must be 'stabilizer' or 'logical'.")

        df = self._require_dataset()
        plot_df = df[df["category"] == category].copy()
        panel_labels = list(dict.fromkeys(plot_df["display_name"]))
        operators = list(dict.fromkeys(plot_df["operator"]))
        rounds = sorted(plot_df["round"].unique().tolist())
        style_map = self._operator_style_map(operators)

        fig, axes = plt.subplots(
            1,
            len(panel_labels),
            figsize=figsize,
            squeeze=False,
            sharex=True,
            sharey=True,
        )
        legend_entries = {}
        ylabel = "|<S>|" if category == "stabilizer" else "|<L>|"

        for col, display_name in enumerate(panel_labels):
            ax = axes[0][col]
            ax.set_title(display_name, fontsize=18)
            ax.grid(True, alpha=0.3)
            panel_df = plot_df[plot_df["display_name"] == display_name]

            for operator in operators:
                op_df = panel_df[panel_df["operator"] == operator]
                if op_df.empty:
                    continue
                color, marker = style_map[operator]
                grouped = op_df.groupby("round")["fidelity"]
                x = sorted(grouped.groups.keys())
                y = grouped.mean().reindex(x).tolist()
                yerr = grouped.std(ddof=1).fillna(0.0).reindex(x).tolist()
                eb = ax.errorbar(
                    x,
                    y,
                    yerr=yerr,
                    fmt=marker,
                    color=color,
                    capsize=3,
                    linestyle="None",
                    zorder=3,
                )
                if operator not in legend_entries:
                    legend_entries[operator] = eb.lines[0]

                if show_violin:
                    vp = ax.violinplot(
                        [grouped.get_group(round_idx).tolist() for round_idx in x],
                        positions=x,
                        widths=0.6,
                        showmeans=False,
                        showextrema=False,
                    )
                    for body in vp["bodies"]:
                        body.set_facecolor(color)
                        body.set_edgecolor(color)
                        body.set_alpha(0.2)

                if show_replicates:
                    for round_idx in x:
                        vals = grouped.get_group(round_idx).tolist()
                        ax.scatter(
                            [round_idx] * len(vals),
                            vals,
                            color=color,
                            alpha=0.05,
                            s=4,
                            zorder=2,
                        )

            if col == 0:
                ax.set_ylabel(ylabel, fontsize=16)
            ax.set_xlabel("MDR rounds", fontsize=16)
            ax.set_xticks(rounds)

        fig.legend(
            list(legend_entries.values()),
            list(legend_entries.keys()),
            loc="center left",
            bbox_to_anchor=(0.93, 0.5),
            fontsize=14,
        )
        fig.tight_layout(rect=[0, 0, 0.935, 1.0])

        out_path = Path(save_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(out_path, dpi=300, bbox_inches="tight")
        if "agg" not in plt.get_backend().lower():
            plt.show()
        plt.close(fig)
        return out_path

    def plot_combined_fidelity(
        self,
        save_path: str | Path,
        figsize: Tuple[int, int] = (18, 10),
    ) -> Path:
        """
        Plot stabilizer and logical fidelity panels in one combined figure.

        Args:
            save_path: Destination PDF path.
            figsize: Figure size in inches.

        Returns:
            Path: Written output path.
        """
        df = self._require_dataset()
        categories = ["stabilizer", "logical"]
        panel_labels = list(dict.fromkeys(df["display_name"]))

        fig, axes = plt.subplots(
            2,
            len(panel_labels),
            figsize=figsize,
            squeeze=False,
            sharex="col",
        )
        legend_entries = {}

        for row, category in enumerate(categories):
            cat_df = df[df["category"] == category]
            operators = list(dict.fromkeys(cat_df["operator"]))
            style_map = self._operator_style_map(operators)
            rounds = sorted(cat_df["round"].unique().tolist())
            ylabel = "|<S>|" if category == "stabilizer" else "|<L>|"

            for col, display_name in enumerate(panel_labels):
                ax = axes[row][col]
                if row == 0:
                    ax.set_title(display_name, fontsize=18)
                ax.grid(True, alpha=0.3)
                panel_df = cat_df[cat_df["display_name"] == display_name]

                for operator in operators:
                    op_df = panel_df[panel_df["operator"] == operator]
                    if op_df.empty:
                        continue
                    color, marker = style_map[operator]
                    grouped = op_df.groupby("round")["fidelity"]
                    x = sorted(grouped.groups.keys())
                    y = grouped.mean().reindex(x).tolist()
                    yerr = grouped.std(ddof=1).fillna(0.0).reindex(x).tolist()
                    eb = ax.errorbar(
                        x,
                        y,
                        yerr=yerr,
                        fmt=marker,
                        color=color,
                        capsize=3,
                        linestyle="None",
                        zorder=3,
                    )
                    if operator not in legend_entries:
                        legend_entries[operator] = eb.lines[0]

                    vp = ax.violinplot(
                        [grouped.get_group(round_idx).tolist() for round_idx in x],
                        positions=x,
                        widths=0.6,
                        showmeans=False,
                        showextrema=False,
                    )
                    for body in vp["bodies"]:
                        body.set_facecolor(color)
                        body.set_edgecolor(color)
                        body.set_alpha(0.2)

                if col == 0:
                    ax.set_ylabel(ylabel, fontsize=16)
                if row == len(categories) - 1:
                    ax.set_xlabel("MDR rounds", fontsize=16)
                    ax.set_xticks(rounds)

        fig.legend(
            list(legend_entries.values()),
            list(legend_entries.keys()),
            loc="center left",
            bbox_to_anchor=(0.93, 0.5),
            fontsize=14,
        )
        fig.tight_layout(rect=[0, 0, 0.935, 1.0])

        out_path = Path(save_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(out_path, dpi=300, bbox_inches="tight")
        if "agg" not in plt.get_backend().lower():
            plt.show()
        plt.close(fig)
        return out_path
